- name: Install gertty
  pip:
    name: gertty
    extra_args: '--user'

- name: Copy default opendev configuration
  copy:
    src: ~/.local/share/gertty/examples/opendev-gertty.yaml
    dest: ~/.gertty.yaml
    remote_src: true
    mode: 0600
