- name: Install gertty
  pip:
    name: gertty
    extra_args: '--user'

- name: Check if gerrty is already configured
  stat:
    path: ~/.gertty.yaml
  register: gertty_yaml

- name: Copy default opendev configuration
  copy:
    src: ~/.local/share/gertty/examples/opendev-gertty.yaml
    dest: ~/.gertty.yaml
    remote_src: true
    mode: 0600
  when: not gertty_yaml.stat.exists
