- name: Install i3 and dependencies
  package:
    name:
      - i3
      - i3status
      - dmenu
      - i3lock
      - xbacklight
      - feh
      - compton
      - mozilla-fira-mono-fonts.noarch
  become: true

- name: Create i3 config dir
  file:
    path: ~/.config/i3
    state: directory

- name: Dump i3 config file
  copy:
    src: config
    dest: ~/.config/i3/config

- name: Dump compton config file
  copy:
    content: |
      blur-background = false;
      blur-background-fixed = true;
      blur-kern = "7x7box";
      blur-background-exclude = [
        "class_g = 'i3-frame'",
        "window_type = 'dock'",
        "window_type = 'desktop'",
        "_GTK_FRAME_EXTENTS@:c"
      ];
    dest: ~/.config/compton.conf

- name: Create feh-images
  file:
    path: ~/feh-images
    state: directory

- name: Copy background image
  copy:
    src: "( ._.).png"
    dest: "~/feh-images/( ._.).png"

- name: Create .fehbg
  copy:
    content: |
      #!/bin/sh
      feh --bg-scale '/home/{{ ansible_user }}/feh-images/( ._.).png'
    dest: ~/.fehbg
    mode: u+x
