- hosts: all
  pre_tasks:
    - name: Make sure all packages are up to date
      dnf:
        name: '*'
        state: latest
        update_cache: yes
      become: yes
  roles:
    - i3
    - zsh
    - nvim
    - git
    - rg
    - fzf
    - gertty
    - git-review
    - irssi
