- name: Install neovim dependencies
  pip:
    name: pynvim
    extra_args: '--user'

- name: Install neovim
  package:
    name:
      - neovim
  become: yes

- name: Create neovim config dir
  file:
    path: ~/.config/nvim
    state: directory
    recurse: true

- name: Dump neovim config file
  copy:
    src: init.vim
    dest: ~/.config/nvim/init.vim

- name: Install vundle
  git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    clone: yes
    dest: ~/.vim/bundle/Vundle.vim


# We can't easily detect if this changes anything
# So pretend it doesn't
- name: Clean vim plugins
  command: nvim +"PluginClean" +"qall"
  changed_when: false
  no_log: true

- name: Install vim plugins
  command: nvim +"PluginInstall" +"qall"
  changed_when: false
  no_log: true
